# Mammary Adenoma vs Adenocarcinoma 추출 PoC (v1)
이 노트북은 앞서 설명한 단계별 필터링 절차를 적용하여 `Data/조직검사 결과 매칭(2024)_utf8_pruned.csv`에서 **Mammary Adenoma**와 **Mammary Adenocarcinoma**를 구분합니다.
<sub>규칙 기반 1차 필터와 수동 검토 루프를 묶어 약한 감독(weak supervision) 방식으로 레이블링 비용을 낮추는 PoC 흐름을 검증합니다.</sub>

In [1]:
import pandas as pd
from pathlib import Path
import pyarrow  # ensure parquet engine is available

pd.options.display.max_colwidth = 120

DATA_PATH = Path("../../Data/조직검사 결과 매칭(2023)_utf8_pruned.parquet")
assert DATA_PATH.exists(), f"Missing data file: {DATA_PATH}"

raw_df = pd.read_parquet(DATA_PATH, engine="pyarrow")
raw_df.head()

,INSP_RQST_NO,FOLDER,FILE_NAME,INSP_SRVC_NM,RESULT_PDF,DIAGNOSIS,GROSS_FINDINGS,COMMENTS,MICROSCOPIC_FINDINGS,SITE,SNAPSHOT
0,20230101-117-0007,S23-00019,S23-00019#1###3.svs,Histopathology (1 Site/Lesion)-국내,None,"Mammary adenoma, complex type, completely excised","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...",site1,https://greenvet-lis-prd.s3.ap-northeast-2.amazonaws.com/ASIS/tissue/5b6c281d990f3d112475d9ae11433e47.jpg
1,20230101-117-0007,S23-00019,S23-00019#1###3.svs,Histopathology (1 Site/Lesion)-국내,None,"Mammary adenoma, complex type, completely excised","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...",site1,https://greenvet-lis-prd.s3.ap-northeast-2.amazonaws.com/ASIS/tissue/9fd390a93dda65f981b3ecb4cb79ce05.jpg
2,20230101-124-0008,S23-00020,S23-00020#1#A##4.svs|S23-00020#1#B##5.svs|S23-00020#1#C##6.svs|S23-00020#1#D##9.svs|S23-00020#1#E##0.svs,Histopathology (1 Site/Lesion)-국내,None,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),"Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...",site1,https://greenvet-lis-prd.s3.ap-northeast-2.amazonaws.com/ASIS/tissue/0b15ef622b65280b86bd79e75dbd6c49.jpg
3,20230101-124-0008,S23-00020,S23-00020#1#A##4.svs|S23-00020#1#B##5.svs|S23-00020#1#C##6.svs|S23-00020#1#D##9.svs|S23-00020#1#E##0.svs,Histopathology (1 Site/Lesion)-국내,None,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),"Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...",site1,https://greenvet-lis-prd.s3.ap-northeast-2.amazonaws.com/ASIS/tissue/16adf94ee82d9625092323b1446fe909.jpg
4,20230101-124-0008,S23-00020,S23-00020#1#A##4.svs|S23-00020#1#B##5.svs|S23-00020#1#C##6.svs|S23-00020#1#D##9.svs|S23-00020#1#E##0.svs,Histopathology (1 Site/Lesion)-국내,None,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),"Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...",site1,https://greenvet-lis-prd.s3.ap-northeast-2.amazonaws.com/ASIS/tissue/1c7271f22dfa4f9bdcca11e6ce82f14e.jpg

## 1. 스키마와 초기 건수 확인

<sub>스키마와 총 건수를 미리 확인해야 이후 필터링에서 열 이름 오타나 누락으로 인한 정보 손실을 방지할 수 있습니다.</sub>

In [2]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48689 entries, 0 to 48688
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   INSP_RQST_NO          48689 non-null  object
 1   FOLDER                48689 non-null  object
 2   FILE_NAME             48689 non-null  object
 3   INSP_SRVC_NM          48689 non-null  object
 4   RESULT_PDF            6 non-null      object
 5   DIAGNOSIS             48689 non-null  object
 6   GROSS_FINDINGS        48677 non-null  object
 7   COMMENTS              48684 non-null  object
 8   MICROSCOPIC_FINDINGS  48676 non-null  object
 9   SITE                  48689 non-null  object
 10  SNAPSHOT              48687 non-null  object
dtypes: object(11)
memory usage: 4.1+ MB

## 2. 텍스트 정규화 도우미
소문자 변환, HTML `<br>` 제거, 공백 정리, 그리고 느슨한 매칭을 위한 알파벳 전용 보조 문자열을 생성합니다.
<sub>서술문이 길거나 HTML 줄바꿈이 섞인 경우도 일관된 형태로 맞추기 위해 정규화를 먼저 수행합니다 (예: `Mammary adenocarcinoma<br>complete excision` → `mammary adenocarcinoma complete excision`).</sub>

In [3]:
import re

def normalize_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.lower()
    s = s.replace('<br>', ' ')
    s = re.sub(r"[^a-z0-9\s]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def alpha_only(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.lower()
    s = re.sub(r"[^a-z\s]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

norm_cols = ['DIAGNOSIS', 'GROSS_FINDINGS', 'COMMENTS', 'MICROSCOPIC_FINDINGS']
norm_df = raw_df.copy()
for col in norm_cols:
    norm_df[f"{col}_norm"] = norm_df[col].apply(normalize_text)
    norm_df[f"{col}_alpha"] = norm_df[col].apply(alpha_only)

norm_df[[c for c in norm_df.columns if c.endswith('_norm')]].head(10)

,DIAGNOSIS_norm,GROSS_FINDINGS_norm,COMMENTS_norm,MICROSCOPIC_FINDINGS_norm
0,mammary adenoma complex type completely excised,a single mammary mass 0 5 x 0 5 x 0 5 cm right 3rd 4th excised and all processed first occurrence no regional lymph ...,complex type multicentric,tubule complex type
1,mammary adenoma complex type completely excised,a single mammary mass 0 5 x 0 5 x 0 5 cm right 3rd 4th excised and all processed first occurrence no regional lymph ...,complex type multicentric,tubule complex type
2,hepatic necrosis with severe hemorrhage and vacular atypia see comments,liver a single mass 5 x 4 x 3 cm first occurrence no regional lymph nodes enlargement 1 ct caudate lobe 1 cm mass 1 ...,cyst abscess hematoma hepatocellular carcinoma hemangiosarcoma 3 vascular atypia mass,3 1 1 2 vascular atypia 3 4 periportal area hyperplaisa pigment granulomas
3,hepatic necrosis with severe hemorrhage and vacular atypia see comments,liver a single mass 5 x 4 x 3 cm first occurrence no regional lymph nodes enlargement 1 ct caudate lobe 1 cm mass 1 ...,cyst abscess hematoma hepatocellular carcinoma hemangiosarcoma 3 vascular atypia mass,3 1 1 2 vascular atypia 3 4 periportal area hyperplaisa pigment granulomas
4,hepatic necrosis with severe hemorrhage and vacular atypia see comments,liver a single mass 5 x 4 x 3 cm first occurrence no regional lymph nodes enlargement 1 ct caudate lobe 1 cm mass 1 ...,cyst abscess hematoma hepatocellular carcinoma hemangiosarcoma 3 vascular atypia mass,3 1 1 2 vascular atypia 3 4 periportal area hyperplaisa pigment granulomas
5,hepatic necrosis with severe hemorrhage and vacular atypia see comments,liver a single mass 5 x 4 x 3 cm first occurrence no regional lymph nodes enlargement 1 ct caudate lobe 1 cm mass 1 ...,cyst abscess hematoma hepatocellular carcinoma hemangiosarcoma 3 vascular atypia mass,3 1 1 2 vascular atypia 3 4 periportal area hyperplaisa pigment granulomas
6,mammary adenoma complex type completely excised,a single mammary mass 3 x 3 x 2 cm excised first occurrence no regional lymph node enlargement,complex type multicentric,tubule complex type multifocal
7,mammary adenoma complex type completely excised,a single mammary mass 3 x 3 x 2 cm excised first occurrence no regional lymph node enlargement,complex type multicentric,tubule complex type multifocal
8,portal vein hypoperfusion with central lipogranulomas vacuolar hepatopathy and mild cholestasis,diffuse hepatic lesion trucut biopsy all processed first occurrence no regional lymph node enlargement pss,pss pss hepatic microvascular dysplasia portal vein hypoplasia arteriovenous fistula pss lipogranuloma pss pss alp,trucut biopsy portal triad arteriolar profiles multifocal zone 3
9,portal vein hypoperfusion with central lipogranulomas vacuolar hepatopathy and mild cholestasis,diffuse hepatic lesion trucut biopsy all processed first occurrence no regional lymph node enlargement pss,pss pss hepatic microvascular dysplasia portal vein hypoplasia arteriovenous fistula pss lipogranuloma pss pss alp,trucut biopsy portal triad arteriolar profiles multifocal zone 3

## 3. 키워드 규칙
Adenoma와 Adenocarcinoma 각각에 대해 확정 매칭용 기본 패턴과 다른 컬럼의 보조 컨텍스트 용어를 정의합니다.
<sub>자유 서술식으로 입력된 진단명을 포착하기 위해 강한 패턴과 약한 보조 컨텍스트를 분리해 관리하고, 두 진단군을 분리하는 데 핵심이 되는 malignant 표현(`carcinoma`, `malignant`, `invasive` 등)을 별도로 모읍니다.</sub>

In [4]:
primary_patterns = {
    'adenoma': [
        r"mammary adenom",
        r"mamary adenom",  # common misspelling
        r"mammary benign adenom",
        r"apocrine or mammary adenom",
        r"mammary adenom[ae]",
        r"mammary\s+gland\s+adenom",
    ],
    'adenocarcinoma': [
        r"mammary adenocarcin",
        r"mammary carcinoma",
        r"mammary\s+gland\s+adenocarcin",
        r"mammary\s+gland\s+carcinoma",
        r"mammary malignant tumor",
    ],
}

# 전문가가 확실한 표현을 추가할 때 사용 (예: r"mammary gland adenoma")
custom_primary_patterns = {
    'adenoma': [],
    'adenocarcinoma': [],
}

# 지원 컬럼별 기본 보조 키워드
support_keywords = {
    'adenoma': {
        'COMMENTS': ["adenoma", "유선", "apocrine", "benign", "adenomatous"],
        'MICROSCOPIC_FINDINGS': ["adenoma", "lobule", "capsulated", "ductal", "benign"],
        'GROSS_FINDINGS': ["mammary", "乳腺", "mamary", "mass", "nodule"],
    },
    'adenocarcinoma': {
        'COMMENTS': ["adenocarcinoma", "carcinoma", "malignant", "invasive", "metastatic", "anaplastic"],
        'MICROSCOPIC_FINDINGS': ["carcinoma", "adenocarcinoma", "malignant", "invasive", "anaplastic", "pleomorphic"],
        'GROSS_FINDINGS': ["mammary", "mamary", "ulcer", "hemorrhage", "necrosis", "irregular"],
    },
}

# 전문가가 보조 키워드를 추가할 때 사용 (컬럼별 리스트를 확장)
custom_support_keywords = {
    'adenoma': {
        'COMMENTS': [],
        'MICROSCOPIC_FINDINGS': [],
        'GROSS_FINDINGS': [],
    },
    'adenocarcinoma': {
        'COMMENTS': [],
        'MICROSCOPIC_FINDINGS': [],
        'GROSS_FINDINGS': [],
    },
}

# 느슨한 공존 판정을 위한 기본 용어
loose_terms = {
    'adenoma': ["mammary", "mamary"],
    'adenocarcinoma': ["mammary", "mamary"],
}

all_primary_patterns = {
    label: pats + custom_primary_patterns.get(label, [])
    for label, pats in primary_patterns.items()
}

merged_support_keywords = {
    label: {
        col: keywords + custom_support_keywords.get(label, {}).get(col, [])
        for col, keywords in support_map.items()
    }
    for label, support_map in support_keywords.items()
}

## 4. 점수 산정 함수
- 진단 컬럼에 확정 패턴 매칭 시 +2 (adenoma/adenocarcinoma 별도 집계)
- 알파벳 전용 문자열에서 'mammary/mamary'와 핵심 진단 토큰(adenoma vs carcinoma)이 함께 등장하면 +1
- 지원 컬럼에 보조 키워드가 있으면 컬럼당 +1
- 최종 라벨: 점수가 더 큰 쪽을 우선하며, 둘 다 0이면 `none`, 동률이면 `uncertain`
<sub>양성과 악성을 동일한 `mammary` 해부 부위 안에서 구분하기 위해 두 집합을 병렬로 점수화합니다. 동시에 등장하거나 애매한 경우를 `uncertain`으로 남겨 수동 검토 대상을 명확히 합니다.</sub>

In [5]:

import pandas as pd

mammary_context_terms = ['mammary', 'mamary']
mammary_context_korean = ['유선', '乳腺']

def has_mammary_context(row):
    raw_fields = ' '.join(
        str(row.get(col, ''))
        for col in ['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS']
        if isinstance(row.get(col, ''), str)
    ).lower().replace('<br>', ' ')
    if any(term in row['DIAGNOSIS_norm'] for term in mammary_context_terms):
        return True
    return any(term in raw_fields for term in mammary_context_terms + mammary_context_korean)

def score_row(row):
    scores = {'adenoma': 0, 'adenocarcinoma': 0}
    diag_norm = row['DIAGNOSIS_norm']
    diag_alpha = row['DIAGNOSIS_alpha']
    diag_tokens = set(diag_alpha.split())

    for label in scores:
        # primary patterns
        if any(re.search(pat, diag_norm) for pat in all_primary_patterns[label]):
            scores[label] += 2

        # loose co-occurrence within diagnosis
        if label == 'adenoma':
            if diag_tokens.intersection(loose_terms[label]) and 'adenoma' in diag_tokens:
                scores[label] += 1
        else:
            if diag_tokens.intersection(loose_terms[label]) and (
                'carcinoma' in diag_tokens or 'adenocarcinoma' in diag_tokens
            ):
                scores[label] += 1

        # supporting columns
        for col, keywords in merged_support_keywords[label].items():
            text = row[f"{col}_norm"]
            if any(kw in text for kw in keywords):
                scores[label] += 1

    mammary_ok = has_mammary_context(row)

    if scores['adenoma'] == 0 and scores['adenocarcinoma'] == 0:
        label = 'none'
    elif not mammary_ok:
        label = 'uncertain'
    elif scores['adenoma'] > scores['adenocarcinoma']:
        label = 'mammary_adenoma'
    elif scores['adenocarcinoma'] > scores['adenoma']:
        label = 'mammary_adenocarcinoma'
    else:
        label = 'uncertain'

    return pd.Series({
        'score_adenoma': scores['adenoma'],
        'score_adenocarcinoma': scores['adenocarcinoma'],
        'label': label,
    })

scores_df = norm_df.apply(score_row, axis=1)
norm_df = pd.concat([norm_df, scores_df], axis=1)

norm_df[['DIAGNOSIS', 'score_adenoma', 'score_adenocarcinoma', 'label']].head(20)

,DIAGNOSIS,score_adenoma,score_adenocarcinoma,label
0,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
1,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
2,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),1,1,uncertain
3,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),1,1,uncertain
4,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),1,1,uncertain
5,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),1,1,uncertain
6,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
7,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
8,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis",0,0,none
9,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis",0,0,none
10,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis",0,0,none
11,Within normal limit,0,0,none
12,Within normal limit,0,0,none
13,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
14,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
15,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
16,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
17,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
18,"Mammary adenoma, complex type, completely excised",4,1,mammary_adenoma
19,Reactive papilloma,1,0,uncertain

In [6]:
# adenoma로 분류된 행 미리보기 (전수 확인용)
adenoma_rows = norm_df[norm_df['label'] == 'mammary_adenoma']
adenoma_rows[['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS', 'score_adenoma']]

,DIAGNOSIS,COMMENTS,MICROSCOPIC_FINDINGS,GROSS_FINDINGS,score_adenoma
0,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...",4
1,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...",4
6,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 유선 유래의 한 개의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (3 x 3 x 2 cm); excised<br>First occurrence, no regional lymph node enlargement",4
7,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 유선 유래의 한 개의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (3 x 3 x 2 cm); excised<br>First occurrence, no regional lymph node enlargement",4
13,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...",소엽성 과증식을 나타내는 유선 사이에 형성된 한 개의 종양성 종괴가 주요 소견입니다. 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 ...,"A single mammary mass (3 x 3 x 3 cm); excised<br>First occurrence, no regional lymph node enlargement",4
...,...,...,...,...,...
48630,"<p>1) Mammary benign mixed tumor, completely excised<br>2) Mammary gland adenoma, simple type, completely excised</p>","<p>개의 유선 종양은 중성화하지 않은 암컷 개체에서 가장 흔한 종양입니다. 성호르몬(e.g. estrogen, progestin)이 risk factor로 작용하여 첫 번째~두 번째 발정 이전에 중성화가 이...",<p>의뢰된 좌측 3-5번 유선 검체 저배율 시야에서는 2개의 피막화된 유선 종양이 확인됩니다. 1) 그중 약 7.05mm 크기의 결절은 뼈와 연골의 화생을 동반한 mixed type의 유선 종양으로 확인되며...,"<p>Specimen: Mammary<br>Appearance: 다발 multiple, Size: 2X2X2cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<b...",4
48646,"<p>Mammary adenomas, complex type</p>",<p>의뢰된 유선 조직 내 2개의 경계가 명확한 (직경 약 1.8-10.7 mm) 유선 종양성 결절들이 확인됩니다. 종양은 모두 선상피 세포와 근상피 세포의 복합 증식에 의한 양성 종양인 complex typ...,"<p>피부가 포함된 조직 내 2개 결절 구조를 포함한 장축 1단면을 두 조각으로 나누어 제작-판독하였습니다. 2개의 결절은 모두 유선 유래의 종양성 결절로, 각각의 경계는 명확한 편이었으며, 유선 선상피 세포...","<p>Specimen: Mammary<br>Appearance: 산재 diffuse, Size: 2X2X2cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<br...",4
48647,"<p>Mammary adenomas, complex type</p>",<p>의뢰된 유선 조직 내 2개의 경계가 명확한 (직경 약 1.8-10.7 mm) 유선 종양성 결절들이 확인됩니다. 종양은 모두 선상피 세포와 근상피 세포의 복합 증식에 의한 양성 종양인 complex typ...,"<p>피부가 포함된 조직 내 2개 결절 구조를 포함한 장축 1단면을 두 조각으로 나누어 제작-판독하였습니다. 2개의 결절은 모두 유선 유래의 종양성 결절로, 각각의 경계는 명확한 편이었으며, 유선 선상피 세포...","<p>Specimen: Mammary<br>Appearance: 산재 diffuse, Size: 2X2X2cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<br...",4
48648,"<p>Mammary adenomas, complex type</p>",<p>의뢰된 유선 조직 내 2개의 경계가 명확한 (직경 약 1.8-10.7 mm) 유선 종양성 결절들이 확인됩니다. 종양은 모두 선상피 세포와 근상피 세포의 복합 증식에 의한 양성 종양인 complex typ...,"<p>피부가 포함된 조직 내 2개 결절 구조를 포함한 장축 1단면을 두 조각으로 나누어 제작-판독하였습니다. 2개의 결절은 모두 유선 유래의 종양성 결절로, 각각의 경계는 명확한 편이었으며, 유선 선상피 세포...","<p>Specimen: Mammary<br>Appearance: 산재 diffuse, Size: 2X2X2cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<br...",4
48649,"<p>Mammary adenomas, complex type</p>",<p>의뢰된 유선 조직 내 2개의 경계가 명확한 (직경 약 1.8-10.7 mm) 유선 종양성 결절들이 확인됩니다. 종양은 모두 선상피 세포와 근상피 세포의 복합 증식에 의한 양성 종양인 complex typ...,"<p>피부가 포함된 조직 내 2개 결절 구조를 포함한 장축 1단면을 두 조각으로 나누어 제작-판독하였습니다. 2개의 결절은 모두 유선 유래의 종양성 결절로, 각각의 경계는 명확한 편이었으며, 유선 선상피 세포...","<p>Specimen: Mammary<br>Appearance: 산재 diffuse, Size: 2X2X2cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<br...",4

In [7]:
# adenocarcinoma로 분류된 행 미리보기 (전수 확인용)
adenocarcinoma_rows = norm_df[norm_df['label'] == 'mammary_adenocarcinoma']
adenocarcinoma_rows[['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS', 'score_adenocarcinoma']]

,DIAGNOSIS,COMMENTS,MICROSCOPIC_FINDINGS,GROSS_FINDINGS,score_adenocarcinoma
23,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2
24,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2
25,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2
26,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2
43,Mammary carcinoma (grade 2),"현재 Intermediate-grade의 악성종양이 발생하였으며, 종양 전체를 포함한 외과적 절제가 확인되었습니다. 본 검체의 조직검사 상에서는 림프관 내 전이 소견이 관찰되지 않았지만, 종양의 악성도가 높고...","의뢰된 유선 mass에서는 악성도 높은 유선종양이 발생하였습니다. 유선도관 상피유래의 종양으로, 도관의 본래 구조(tubule formation)를 중등도로 유지하는 종양이 여러 mass를 이루며 결합조직 내...",Specimen : Mammary / Operation : incisional / Size : 1.5X1.5X1.5<br>Specimen Appearance : 단독 single<br>Recurrence : ...,5
...,...,...,...,...,...
48465,"<p>Mammary comedocarcinoma, Grade 2</p>","<p>SITE 1으로 의뢰된 5번 유선 조직 내에서 악성도가 높고, 예후가 불량한 유형의 유선 종양인 mammary comedocarcinoma 소견이 확인되었습니다. 이 유형의 악성 유선 종양은 흉-복강 내...","<p>피부가 포함된 조직의 1단면을 2개의 블록에 나누어 제작-판독하였습니다. 진피와 피하층에 형성된 직경 3.7 cm 가량의 범위에 형성된 악성 유선 종양 결절들이 주요 소견으로, 각각의 결절성 종괴의 경계...","<p>Specimen: Mammary<br>Appearance: 다발 multiple, Size: 1X1X1cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<b...",2
48466,"<p>Mammary comedocarcinoma, Grade 2</p>","<p>SITE 1으로 의뢰된 5번 유선 조직 내에서 악성도가 높고, 예후가 불량한 유형의 유선 종양인 mammary comedocarcinoma 소견이 확인되었습니다. 이 유형의 악성 유선 종양은 흉-복강 내...","<p>피부가 포함된 조직의 1단면을 2개의 블록에 나누어 제작-판독하였습니다. 진피와 피하층에 형성된 직경 3.7 cm 가량의 범위에 형성된 악성 유선 종양 결절들이 주요 소견으로, 각각의 결절성 종괴의 경계...","<p>Specimen: Mammary<br>Appearance: 다발 multiple, Size: 1X1X1cm<br>Operation: excisional<br>Recurrence: N, Lymph: N<b...",2
48583,"<p>Mammary carcinoma, simple type, grade 2, completely excised<br>Lymphatic invasion</p>","<p>의뢰된 유선 종괴는 grade 2의 악성 유선 종양으로 진단되었습니다. 개의 유선 종양은 중성화 하지 않은 암컷에서 가장 빈번하게 발생하는 종양으로, 프로게스틴, 에스트로겐 등 성호르몬의 영향을 받습니다...",<p>의뢰된 유선 검체 저배율 시야에서는 유선 종양의 공격적인 증식이 확인됩니다. 종양은 높은 기질 침습성을 띠며 진피층 상부와 피하지방 심부까지 파급되어 있습니다. 종양세포는 세관 확은 구조를 이루며 증식했...,"<p>Specimen: Mammary<br>Appearance: 단독 single, Size: 0X0X0cm<br>Operation: incisional<br>Recurrence: Y, Lymph: Y<br>...",4
48584,"<p>Mammary carcinoma, simple type, grade 2, completely excised<br>Lymphatic invasion</p>","<p>의뢰된 유선 종괴는 grade 2의 악성 유선 종양으로 진단되었습니다. 개의 유선 종양은 중성화 하지 않은 암컷에서 가장 빈번하게 발생하는 종양으로, 프로게스틴, 에스트로겐 등 성호르몬의 영향을 받습니다...",<p>의뢰된 유선 검체 저배율 시야에서는 유선 종양의 공격적인 증식이 확인됩니다. 종양은 높은 기질 침습성을 띠며 진피층 상부와 피하지방 심부까지 파급되어 있습니다. 종양세포는 세관 확은 구조를 이루며 증식했...,"<p>Specimen: Mammary<br>Appearance: 단독 single, Size: 0X0X0cm<br>Operation: incisional<br>Recurrence: Y, Lymph: Y<br>...",4
48585,"<p>Mammary carcinoma, simple type, grade 2, completely excised<br>Lymphatic invasion</p>","<p>의뢰된 유선 종괴는 grade 2의 악성 유선 종양으로 진단되었습니다. 개의 유선 종양은 중성화 하지 않은 암컷에서 가장 빈번하게 발생하는 종양으로, 프로게스틴, 에스트로겐 등 성호르몬의 영향을 받습니다...",<p>의뢰된 유선 검체 저배율 시야에서는 유선 종양의 공격적인 증식이 확인됩니다. 종양은 높은 기질 침습성을 띠며 진피층 상부와 피하지방 심부까지 파급되어 있습니다. 종양세포는 세관 확은 구조를 이루며 증식했...,"<p>Specimen: Mammary<br>Appearance: 단독 single, Size: 0X0X0cm<br>Operation: incisional<br>Recurrence: Y, Lymph: Y<br>...",4

## 5. 경계 사례 검토
점수가 동률이거나 둘 다 낮은 행을 확인하여 잘못된 분류를 보정합니다.
<sub>예: `diagnosis`에 adenoma, `micro`에 carcinoma가 언급된 혼합 표현을 사람이 빠르게 검토해 룰셋을 개선합니다.</sub>

In [8]:
uncertain = norm_df[norm_df['label'].isin(['uncertain', 'none'])]
uncertain[['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS', 'score_adenoma', 'score_adenocarcinoma']].head(10)

,DIAGNOSIS,COMMENTS,MICROSCOPIC_FINDINGS,GROSS_FINDINGS,score_adenoma,score_adenocarcinoma
2,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...","Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",1,1
3,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...","Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",1,1
4,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...","Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",1,1
5,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),뽀미의 의뢰된 조직은 파열된 Cyst 구조로 보이는 결합조직 주변으로 괴사성 변화와 광범위한 출혈과 염증세포의 침윤이 관찰되었습니다. 파열 부위 인근의 괴사와 염증이 너무 심하게 진행되어 있어 기존 낭성 병변...,"의뢰된 간 조직의 3개 단면이 제작-판독되었습니다. 1개 단면은 파열된 낭성 구조물 주변으로 괴사된 간세포와 결합조직, 출혈로 인해 판독이 불가한 부분을 광범위하게 포함하고 있었습니다(사진1, 사진2). 괴사...","Liver<br>A single mass (5 x 4 x 3 cm)<br>First occurrence, No regional lymph nodes enlargement<br>1년 전 CT: caudate l...",1,1
8,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis","의뢰된 간 조직의 조직병리학적 소견은 간문맥 관류감소 시 나타날 수 있는 변화로, 제공된 임상정보(간문맥단락, PSS)와 일치하는 소견입니다. 일반적으로 문맥 혈관의 기형은 PSS, 간 미세혈관 이형성증/문맥...",Trucut biopsy 간 조직은 모두 제작되어 두 단면에 대한 조직병리학적 검사가 진행되었습니다. 간세동이(portal triad)의 문맥은 감소했거나 소실되었으며 세동맥(arteriolar profile...,"Diffuse hepatic lesion; Trucut biopsy, all processed<br>First occurrence, no regional lymph node enlargement<br>PSS",0,0
9,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis","의뢰된 간 조직의 조직병리학적 소견은 간문맥 관류감소 시 나타날 수 있는 변화로, 제공된 임상정보(간문맥단락, PSS)와 일치하는 소견입니다. 일반적으로 문맥 혈관의 기형은 PSS, 간 미세혈관 이형성증/문맥...",Trucut biopsy 간 조직은 모두 제작되어 두 단면에 대한 조직병리학적 검사가 진행되었습니다. 간세동이(portal triad)의 문맥은 감소했거나 소실되었으며 세동맥(arteriolar profile...,"Diffuse hepatic lesion; Trucut biopsy, all processed<br>First occurrence, no regional lymph node enlargement<br>PSS",0,0
10,"Portal vein hypoperfusion with central lipogranulomas, vacuolar hepatopathy and mild cholestasis","의뢰된 간 조직의 조직병리학적 소견은 간문맥 관류감소 시 나타날 수 있는 변화로, 제공된 임상정보(간문맥단락, PSS)와 일치하는 소견입니다. 일반적으로 문맥 혈관의 기형은 PSS, 간 미세혈관 이형성증/문맥...",Trucut biopsy 간 조직은 모두 제작되어 두 단면에 대한 조직병리학적 검사가 진행되었습니다. 간세동이(portal triad)의 문맥은 감소했거나 소실되었으며 세동맥(arteriolar profile...,"Diffuse hepatic lesion; Trucut biopsy, all processed<br>First occurrence, no regional lymph node enlargement<br>PSS",0,0
11,Within normal limit,의뢰된 위 검체는 World Small Animal Veterinary Association Gastrointestinal Standardization Group이 제안한 기준에 따라 판독되었습니다.<br>위...,The samples examined are superficial epithelium and lamina propria. The sections consist of intact epithelium and du...,"Stomach; Endoscopic biopsy (1 x 1 x 1 cm), all processed<br>First occurrence, no regional lymph node enlargement<br>...",0,0
12,Within normal limit,의뢰된 위 검체는 World Small Animal Veterinary Association Gastrointestinal Standardization Group이 제안한 기준에 따라 판독되었습니다.<br>위...,The samples examined are superficial epithelium and lamina propria. The sections consist of intact epithelium and du...,"Stomach; Endoscopic biopsy (1 x 1 x 1 cm), all processed<br>First occurrence, no regional lymph node enlargement<br>...",0,0
19,Reactive papilloma,"피부 및 점막에서 발생하는 유두종(papilloma)은 일반적으로 바이러스에 의해 발생합니다. 간혹 악성의 유두종도 있으나 일반적으로 발생하는 유두종은 양성입니다. 바이러스로 인한 유두종을 감별하기 위해, 조...",An exophytic mass with numerous blunt-edged delicate fronds composed of hyperplastic non-keratinizing squamous cells...,Specimen : Skin / Operation : excisional / Size : 1.5X1.5X1.5<br>Specimen Appearance : 다발 multiple<br>Recurrence : Y...,1,0

## 6. 종(개/고양이) 판정
<sub>숫자 표현(예: `두 개`, `3 개의`)에 등장하는 한글 `개`를 개체로 오인하지 않도록, 종을 암시하는 문맥/품종/영문 표현이 있을 때만 점수를 부여합니다. 확신이 어려우면 `uncertain`으로 남깁니다.</sub>

In [9]:
species_patterns = {
    'dog': [
        r"canin",
        r"dog(s)?",
        r"개에서",
        r"개\s*환자",
        r"견",
        r"강아지",
    ],
    'cat': [
        r"felin",
        r"cat(s)?",
        r"고양이에서",
        r"고양이\s*환자",
        r"냥이",
    ],
}

breed_keywords = {
    'dog': [
        'poodle', 'toy', 'miniature', 'retriever', 'bulldog', 'beagle', 'shihtzu', 'shih', 'tzu',
        'yorkshire', 'maltese', 'pom', 'pomeranian', 'spitz', 'jindo', 'shepherd', 'collie',
    ],
    'cat': [
        'persian', 'ragdoll', 'bengal', 'munchkin', 'siam', 'siamese', 'fold', 'norwegian',
        'russian', 'blue', 'sphynx', 'cat',
    ],
}

def normalize_species_text(row):
    text = ' '.join(
        str(row.get(col, ''))
        for col in ['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS']
        if isinstance(row.get(col, ''), str)
    ).lower().replace('<br>', ' ')
    text = re.sub(r"[^0-9a-z가-힣\s]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def score_species(row):
    text = normalize_species_text(row)
    tokens = set(text.split())
    scores = {'dog': 0, 'cat': 0}

    for label, patterns in species_patterns.items():
        for pat in patterns:
            if re.search(pat, text):
                scores[label] += 2

    for label, keywords in breed_keywords.items():
        for kw in keywords:
            if kw in tokens:
                scores[label] += 1

    if scores['dog'] == 0 and scores['cat'] == 0:
        species_label = 'uncertain'
    elif scores['dog'] > scores['cat']:
        species_label = 'dog'
    elif scores['cat'] > scores['dog']:
        species_label = 'cat'
    else:
        species_label = 'uncertain'

    return pd.Series({
        'score_dog': scores['dog'],
        'score_cat': scores['cat'],
        'species_label': species_label,
    })

species_df = norm_df.apply(score_species, axis=1)
norm_df = pd.concat([norm_df, species_df], axis=1)

norm_df[['DIAGNOSIS', 'species_label', 'score_dog', 'score_cat']].head()

,DIAGNOSIS,species_label,score_dog,score_cat
0,"Mammary adenoma, complex type, completely excised",dog,4,0
1,"Mammary adenoma, complex type, completely excised",dog,4,0
2,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),dog,2,0
3,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),dog,2,0
4,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),dog,2,0

## 7. 양성/악성 판정
<sub>악성과 양성 모두에서 흔히 쓰이는 조직명 표현을 규칙으로 점수화하고, 근거가 약하면 `uncertain`으로 남깁니다.</sub>

In [10]:
benign_patterns = [
    r"adenoma",
    r"papilloma",
    r"polyp",
    r"fibroma",
    r"lipoma",
    r"osteoma",
    r"chondroma",
    r"hemangioma",
    r"lymphangioma",
    r"leiomyoma",
    r"rhabdomyoma",
    r"neuroma",
    r"fibroadenoma",
    r"mixed tumor",
    r"melanocytoma",
    r"histiocytoma",
]

malignant_patterns = [
    r"carcinoma",
    r"adenocarcinoma",
    r"sarcoma",
    r"fibrosarcoma",
    r"osteosarcoma",
    r"hemangiosarcoma",
    r"liposarcoma",
    r"leiomyosarcoma",
    r"rhabdomyosarcoma",
    r"carcinosarcoma",
    r"malignant mixed tumor",
    r"melanoma",
    r"lymphoma",
    r"mast cell tumor",
    r"histiocytic sarcoma",
]

behavior_support = {
    'benign': ['benign', '양성'],
    'malignant': ['malignant', 'invasive', 'metastatic', 'metastasis', 'anaplastic', '악성'],
}

def concat_norm_text(row):
    return ' '.join(str(row.get(f"{col}_norm", '')) for col in norm_cols)

def score_behavior(row):
    text = concat_norm_text(row)
    scores = {'benign': 0, 'malignant': 0}

    for pat in benign_patterns:
        if re.search(pat, text):
            scores['benign'] += 2
    for pat in malignant_patterns:
        if re.search(pat, text):
            scores['malignant'] += 2

    for label, keywords in behavior_support.items():
        for kw in keywords:
            if kw in text:
                scores[label] += 1

    if scores['benign'] == 0 and scores['malignant'] == 0:
        behavior_label = 'none'
    elif scores['benign'] > scores['malignant']:
        behavior_label = 'benign'
    elif scores['malignant'] > scores['benign']:
        behavior_label = 'malignant'
    else:
        behavior_label = 'uncertain'

    return pd.Series({
        'score_benign': scores['benign'],
        'score_malignant': scores['malignant'],
        'behavior_label': behavior_label,
    })

behavior_df = norm_df.apply(score_behavior, axis=1)
norm_df = pd.concat([norm_df, behavior_df], axis=1)

norm_df[['DIAGNOSIS', 'behavior_label', 'score_benign', 'score_malignant']].head()

,DIAGNOSIS,behavior_label,score_benign,score_malignant
0,"Mammary adenoma, complex type, completely excised",benign,2,0
1,"Mammary adenoma, complex type, completely excised",benign,2,0
2,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),malignant,0,6
3,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),malignant,0,6
4,Hepatic necrosis with severe hemorrhage and vacular atypia (See comments),malignant,0,6

## 8. 확실 사례 스냅샷
<sub>두 진단군 각각에서 패턴이 제대로 작동하는지, 해부 부위나 진단 요약이 기대대로 나오는지 빠르게 눈으로 검증합니다.</sub>

In [11]:
# adenoma 확실 사례 스냅샷
adenoma_rows = norm_df[norm_df['label'] == 'mammary_adenoma']
adenoma_rows[['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS', 'score_adenoma', 'behavior_label', 'species_label']].head(10)

,DIAGNOSIS,COMMENTS,MICROSCOPIC_FINDINGS,GROSS_FINDINGS,score_adenoma,behavior_label,species_label
0,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...",4,benign,dog
1,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (0.5 x 0.5 x 0.5 cm), right 3rd-4th; excised and all processed<br>First occurrence, no regiona...",4,benign,dog
6,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 유선 유래의 한 개의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (3 x 3 x 2 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
7,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 유선 유래의 한 개의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (3 x 3 x 2 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
13,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...",소엽성 과증식을 나타내는 유선 사이에 형성된 한 개의 종양성 종괴가 주요 소견입니다. 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 ...,"A single mammary mass (3 x 3 x 3 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
14,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...",소엽성 과증식을 나타내는 유선 사이에 형성된 한 개의 종양성 종괴가 주요 소견입니다. 잘 캡슐화되어 병변의 경계는 명확하게 확인되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 ...,"A single mammary mass (3 x 3 x 3 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
15,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (1 x 1 x 1 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
16,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (1 x 1 x 1 cm); excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
17,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (2 x 1 x 1 cm), left 4th; excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog
18,"Mammary adenoma, complex type, completely excised","유선 종양은 암컷 개에서 가장 다발하는 종양으로 중성화 여부나 시기, 호르몬의 영향이 종양의 발생에 영향을 미치는 것으로 알려져 있습니다. 의뢰된 유선 검체는 상피와 근상피세포가 함께 증식하는 complex ...","피하에 형성된 한 개의 유선 유래의 종양성 종괴가 주요 소견으로, 잘 캡슐화되어 병변의 경계는 명확하게 관찰되며 주위 정상 조직을 포함하여 종양은 모두 적출된 것으로 보입니다. 종양세포는 유선을 구성하는 상피...","A single mammary mass (2 x 1 x 1 cm), left 4th; excised<br>First occurrence, no regional lymph node enlargement",4,benign,dog

In [12]:
# adenocarcinoma 확실 사례 스냅샷
adenocarcinoma_rows = norm_df[norm_df['label'] == 'mammary_adenocarcinoma']
adenocarcinoma_rows[['DIAGNOSIS', 'COMMENTS', 'MICROSCOPIC_FINDINGS', 'GROSS_FINDINGS', 'score_adenocarcinoma', 'behavior_label', 'species_label']].head(10)

,DIAGNOSIS,COMMENTS,MICROSCOPIC_FINDINGS,GROSS_FINDINGS,score_adenocarcinoma,behavior_label,species_label
23,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2,malignant,dog
24,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2,malignant,dog
25,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2,malignant,dog
26,"Carcinoma and malignant myoepithelioma, grade 2","의뢰된 유선 종괴는 유선 상피세포 유래의 악성종양(mammary carcinoma)과 근상피세포 유래의 악성 종양(malignant myoepithelioma)이 혼합된 종양으로, 유선 종양 중 비교적 드물게...","표층에서 심부 피하에 걸쳐 형성된 유선 유래의 다결절성 종양성 종괴가 주요 소견으로, 일부 종괴의 중심부는 괴사되었고, 국소적으로 출혈 소견을 나타냅니다. 종양은 캡슐화되어있지 않고 침습성을 나타내며 표층과 ...","A single mammary mass (13 x 8 x 5 cm); excised<br>First occurrence, no regional lymph node enlargement<br>Increased ...",2,malignant,dog
43,Mammary carcinoma (grade 2),"현재 Intermediate-grade의 악성종양이 발생하였으며, 종양 전체를 포함한 외과적 절제가 확인되었습니다. 본 검체의 조직검사 상에서는 림프관 내 전이 소견이 관찰되지 않았지만, 종양의 악성도가 높고...","의뢰된 유선 mass에서는 악성도 높은 유선종양이 발생하였습니다. 유선도관 상피유래의 종양으로, 도관의 본래 구조(tubule formation)를 중등도로 유지하는 종양이 여러 mass를 이루며 결합조직 내...",Specimen : Mammary / Operation : incisional / Size : 1.5X1.5X1.5<br>Specimen Appearance : 단독 single<br>Recurrence : ...,5,malignant,dog
44,Mammary carcinoma (grade 2),"현재 Intermediate-grade의 악성종양이 발생하였으며, 종양 전체를 포함한 외과적 절제가 확인되었습니다. 본 검체의 조직검사 상에서는 림프관 내 전이 소견이 관찰되지 않았지만, 종양의 악성도가 높고...","의뢰된 유선 mass에서는 악성도 높은 유선종양이 발생하였습니다. 유선도관 상피유래의 종양으로, 도관의 본래 구조(tubule formation)를 중등도로 유지하는 종양이 여러 mass를 이루며 결합조직 내...",Specimen : Mammary / Operation : incisional / Size : 1.5X1.5X1.5<br>Specimen Appearance : 단독 single<br>Recurrence : ...,5,malignant,dog
121,"유선, 양성복합종에서 발생한 선암종 <br>(Mammary gland, Carcinoma arising in a complex adenoma)<br>","유선 양성종양과 악성 선암종이 같이 관찰되는 형태로, 발생이 드문 편이여서 예후에 대한 정보는 부족합니다. 선암종이 관찰되는 부위는 grade Ⅱ 정도의 악성으로 판단되기는 하나, 종괴는 전반적으로 잘 구분되...","종괴는 전반적으로 주변조직과 잘 구분되어 있는 편이며, 샘상피세포와 근상피세포가 뒤섞여 증식하고 있고 이들 세포는 세포다형태성 및 분열 활성이 낮은 편입니다. 그러나 국소부위에서 샘상피세포의 염색질이 증가하고...",Specimen : Mammary / Operation : excisional / Size : 3X3X3<br>Specimen Appearance : 단독 single<br>Recurrence : N / Ly...,4,uncertain,uncertain
122,"유선, 양성복합종에서 발생한 선암종 <br>(Mammary gland, Carcinoma arising in a complex adenoma)<br>","유선 양성종양과 악성 선암종이 같이 관찰되는 형태로, 발생이 드문 편이여서 예후에 대한 정보는 부족합니다. 선암종이 관찰되는 부위는 grade Ⅱ 정도의 악성으로 판단되기는 하나, 종괴는 전반적으로 잘 구분되...","종괴는 전반적으로 주변조직과 잘 구분되어 있는 편이며, 샘상피세포와 근상피세포가 뒤섞여 증식하고 있고 이들 세포는 세포다형태성 및 분열 활성이 낮은 편입니다. 그러나 국소부위에서 샘상피세포의 염색질이 증가하고...",Specimen : Mammary / Operation : excisional / Size : 3X3X3<br>Specimen Appearance : 단독 single<br>Recurrence : N / Ly...,4,uncertain,uncertain
123,"유선, 양성복합종에서 발생한 선암종 <br>(Mammary gland, Carcinoma arising in a complex adenoma)<br>","유선 양성종양과 악성 선암종이 같이 관찰되는 형태로, 발생이 드문 편이여서 예후에 대한 정보는 부족합니다. 선암종이 관찰되는 부위는 grade Ⅱ 정도의 악성으로 판단되기는 하나, 종괴는 전반적으로 잘 구분되...","종괴는 전반적으로 주변조직과 잘 구분되어 있는 편이며, 샘상피세포와 근상피세포가 뒤섞여 증식하고 있고 이들 세포는 세포다형태성 및 분열 활성이 낮은 편입니다. 그러나 국소부위에서 샘상피세포의 염색질이 증가하고...",Specimen : Mammary / Operation : excisional / Size : 3X3X3<br>Specimen Appearance : 단독 single<br>Recurrence : N / Ly...,4,uncertain,uncertain
124,"유선, 양성복합종에서 발생한 선암종 <br>(Mammary gland, Carcinoma arising in a complex adenoma)<br>","유선 양성종양과 악성 선암종이 같이 관찰되는 형태로, 발생이 드문 편이여서 예후에 대한 정보는 부족합니다. 선암종이 관찰되는 부위는 grade Ⅱ 정도의 악성으로 판단되기는 하나, 종괴는 전반적으로 잘 구분되...","종괴는 전반적으로 주변조직과 잘 구분되어 있는 편이며, 샘상피세포와 근상피세포가 뒤섞여 증식하고 있고 이들 세포는 세포다형태성 및 분열 활성이 낮은 편입니다. 그러나 국소부위에서 샘상피세포의 염색질이 증가하고...",Specimen : Mammary / Operation : excisional / Size : 3X3X3<br>Specimen Appearance : 단독 single<br>Recurrence : N / Ly...,4,uncertain,uncertain

## 9. 요약 통계
<sub>라벨 분포와 점수 분포를 보면 규칙 조정이 필요한지 판단할 수 있습니다.</sub>

In [13]:
total = len(norm_df)
label_counts = norm_df['label'].value_counts()
behavior_counts = norm_df['behavior_label'].value_counts()
species_counts = norm_df['species_label'].value_counts()

print(f"Total rows: {total}")
print("Mammary label counts:", label_counts)
print("Behavior label counts:", behavior_counts)
print("Species label counts:", species_counts)

score_summary = norm_df[['score_adenoma', 'score_adenocarcinoma', 'score_benign', 'score_malignant', 'score_dog', 'score_cat']].describe()
score_summary

Total rows: 48689
Mammary label counts: label
none                      29265
uncertain                 11589
mammary_adenoma            4346
mammary_adenocarcinoma     3489
Name: count, dtype: int64
Behavior label counts: behavior_label
none         16254
malignant    16166
benign       15505
uncertain      764
Name: count, dtype: int64
Species label counts: species_label
dog          37102
uncertain    10196
cat           1391
Name: count, dtype: int64

,score_adenoma,score_adenocarcinoma,score_benign,score_malignant,score_dog,score_cat
count,48689.000000,48689.000000,48689.000000,48689.000000,48689.000000,48689.000000
mean,0.593830,0.490686,0.743412,1.009612,1.931196,0.187969
std,1.067778,1.100257,1.070792,1.697916,1.190314,0.650774
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000
max,6.000000,6.000000,7.000000,16.000000,8.000000,7.000000

## 10. 정제된 데이터셋 저장
<sub>Adenoma/Adenocarcinoma 라벨과 점수를 포함한 CSV를 남겨 후속 분석·모델 학습에서 동일한 결과를 재사용할 수 있습니다.</sub>

In [14]:
output_cols = [
    'INSP_RQST_NO', 'FOLDER', 'FILE_NAME', 'SITE',
    'DIAGNOSIS', 'GROSS_FINDINGS', 'COMMENTS', 'MICROSCOPIC_FINDINGS',
    'score_adenoma', 'score_adenocarcinoma', 'score_benign', 'score_malignant',
    'score_dog', 'score_cat', 'label', 'behavior_label', 'species_label'
]
curated = norm_df[output_cols].copy()
base_path = Path('./mammary_adenoma_vs_adenocarcinoma_curated')
parquet_path = base_path.with_suffix('.parquet')
csv_path = base_path.with_suffix('.csv')
curated.to_parquet(parquet_path, index=False)
curated.to_csv(csv_path, index=False, encoding='utf-8-sig')
parquet_path, csv_path

(PosixPath('mammary_adenoma_vs_adenocarcinoma_curated.parquet'),
 PosixPath('mammary_adenoma_vs_adenocarcinoma_curated.csv'))

## 11. 다음 단계
- 경계 사례 수동 검토 후 keyword 리스트를 보완합니다.
- 희귀 동의어에 대한 recall을 높이려면 TF-IDF나 임베딩 유사도 방식을 고려합니다.
<sub>규칙→수동 리뷰→키워드 보완→모델 전환의 반복 학습 루프를 염두에 둔 로드맵입니다.</sub>

In [15]:
# 전체 통계 요약
# 전체 행 수, 라벨/행동/종 분포, adenoma/adenocarcinoma 하위집합 분포

total_rows = len(norm_df)

# 라벨 분포 (모든 라벨 포함)
mammary_label_counts_all = norm_df["label"].value_counts().sort_index()
# none/uncertain을 제외한 mammary adenoma/adenocarcinoma만 집계
mammary_label_counts_strict = norm_df[norm_df["label"].isin(["mammary_adenoma", "mammary_adenocarcinoma"])]["label"].value_counts().sort_index()

# 행동(benign/ malignant/ none/ uncertain) 분포
behavior_label_counts = norm_df["behavior_label"].value_counts().sort_index()
# 행동 라벨을 benign/ malignant로만 요약 (none/uncertain 제외)
behavior_label_binary = norm_df[norm_df["behavior_label"].isin(["benign", "malignant"])]["behavior_label"].value_counts().sort_index()

# 종 분포
species_label_counts = norm_df["species_label"].value_counts().sort_index()

# adenoma/adenocarcinoma 하위집합 분포 (none/uncertain 제외)
adenoma_carcinoma = norm_df[norm_df["label"].isin(["mammary_adenoma", "mammary_adenocarcinoma"])]
adenoma_carcinoma_counts = adenoma_carcinoma["label"].value_counts().sort_index()
adenoma_carcinoma_behavior = adenoma_carcinoma["behavior_label"].value_counts().sort_index()
adenoma_carcinoma_species = pd.crosstab(adenoma_carcinoma["species_label"], adenoma_carcinoma["label"]).sort_index()

print(f"Total rows: {total_rows}")
print("Mammary label counts (all labels):")
display(mammary_label_counts_all)

print("Mammary label counts (adenoma/adenocarcinoma only):")
display(mammary_label_counts_strict)

print("Behavior label counts:")
display(behavior_label_counts)

print("Behavior label counts (benign vs malignant only):")
display(behavior_label_binary)

print("Species label counts:")
display(species_label_counts)

print("Adenoma vs adenocarcinoma counts (subset only):")
display(adenoma_carcinoma_counts)

print("Adenoma vs adenocarcinoma behavior counts:")
display(adenoma_carcinoma_behavior)

print("Adenoma vs adenocarcinoma by species:")
display(adenoma_carcinoma_species)

Total rows: 48689
Mammary label counts (all labels):

label
mammary_adenocarcinoma     3489
mammary_adenoma            4346
none                      29265
uncertain                 11589
Name: count, dtype: int64

Mammary label counts (adenoma/adenocarcinoma only):

label
mammary_adenocarcinoma    3489
mammary_adenoma           4346
Name: count, dtype: int64

Behavior label counts:

behavior_label
benign       15505
malignant    16166
none         16254
uncertain      764
Name: count, dtype: int64

Behavior label counts (benign vs malignant only):

behavior_label
benign       15505
malignant    16166
Name: count, dtype: int64

Species label counts:

species_label
cat           1391
dog          37102
uncertain    10196
Name: count, dtype: int64

Adenoma vs adenocarcinoma counts (subset only):

label
mammary_adenocarcinoma    3489
mammary_adenoma           4346
Name: count, dtype: int64

Adenoma vs adenocarcinoma behavior counts:

behavior_label
benign       4298
malignant    3289
none           41
uncertain     207
Name: count, dtype: int64

Adenoma vs adenocarcinoma by species:

label          mammary_adenocarcinoma  mammary_adenoma
species_label
cat                                75               50
dog                              2820             3592
uncertain                         594              704

In [16]:
# mammary_adenoma/mammary_adenocarcinoma 라벨만 별도 저장
adenoma_carcinoma_curated = curated[curated["label"].isin(["mammary_adenoma", "mammary_adenocarcinoma"])].copy()

adenoma_carcinoma_base = Path("./mammary_adenoma_vs_adenocarcinoma_only")
adenoma_carcinoma_parquet = adenoma_carcinoma_base.with_suffix(".parquet")
adenoma_carcinoma_csv = adenoma_carcinoma_base.with_suffix(".csv")

adenoma_carcinoma_curated.to_parquet(adenoma_carcinoma_parquet, index=False)
adenoma_carcinoma_curated.to_csv(adenoma_carcinoma_csv, index=False, encoding="utf-8-sig")

adenoma_carcinoma_parquet, adenoma_carcinoma_csv

(PosixPath('mammary_adenoma_vs_adenocarcinoma_only.parquet'),
 PosixPath('mammary_adenoma_vs_adenocarcinoma_only.csv'))